workflows:
  ios-debug-ipa:
    name: Build iOS Debug IPA (Unsigned)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: Runner
    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS debug (no signing)
        script: |
          flutter build ios --debug --no-codesign

      - name: Create archive manually
        script: |
          mkdir -p build/ios/archive/Products/Applications
          cp -r build/ios/Debug-iphoneos/$APP_NAME.app build/ios/archive/Products/Applications/
          mkdir -p build/ios/archive/dSYMs
          cp -r build/ios/Debug-iphoneos/*.dSYM build/ios/archive/dSYMs/ || true
          cd build/ios/archive
          zip -r ../$APP_NAME.xcarchive *
          cd ../../../

      - name: Package .ipa (unsigned)
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/Debug-iphoneos/$APP_NAME.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r ../$APP_NAME-unsigned.ipa Payload
          cd ../../../
    artifacts:
      - build/ios/$APP_NAME-unsigned.ipa
